sudo: required
dist: xenial
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake qt5-default libqt5svg5-dev wget build-essential libssl-dev
  - wget -O sgx_installer.bin https://download.01.org/intel-sgx/linux-2.3.1/ubuntu16.04/sgx_linux_x64_sdk_2.3.101.46683.bin
  - chmod +x ./sgx_installer.bin
  - echo yes | ./sgx_installer.bin
  - source sgxsdk/environment
script:
  - cd build
  - cmake ..
  - make
