sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake qt5-default libqt5svg5-dev
script:
  - cd build
  - cmake ..
  - make
