version: 2
aliases:
  - &docker_image ubuntu:disco
  - &setup_common |
      apt-get update -qq
      apt-get install -y cmake wget build-essential libssl-dev libncurses-dev libargon2-dev libargon2-0 libargon2-0-dev argon2 pkg-config
      wget -O sgx_installer.bin https://download.01.org/intel-sgx/linux-2.5/ubuntu18.04-server/sgx_linux_x64_sdk_2.5.100.49891.bin
      chmod +x ./sgx_installer.bin
      echo yes | ./sgx_installer.bin
      rm sgx_installer.bin # remove unnecessary package
jobs:
  linux_gcc7:
    docker:
      - image: *docker_image
    steps:
      - checkout
      - run: *setup_common
      - run: |
          apt-get install -qq gcc-7 g++-7
      - run: |
          export CC=gcc-7
          export CXX=g++-7
          source sgxsdk/environment
          cd build
          ./build.sh

  linux_gcc8:
    docker:
      - image: *docker_image
    steps:
      - checkout
      - run: *setup_common
      - run: |
          apt-get install -qq gcc-8 g++-8
      - run: |
          export CC=gcc-8
          export CXX=g++-8
          source sgxsdk/environment
          cd build
          ./build.sh

  linux_clang6:
    docker:
      - image: *docker_image
    steps:
      - checkout
      - run: *setup_common
      - run: |
          apt-get install -qq clang-6.0
      - run: |
          export CC=clang-6.0
          export CXX=clang++-6.0
          source sgxsdk/environment
          cd build
          ./build.sh
workflows:
  version: 2
  secpass_builds:
    jobs:
      - linux_gcc7
      - linux_gcc8
      - linux_clang6
